"""
The face engine, ported from ``src/brand/face.ts``.

This is a deliberate second copy of the geometry, and the reason is worth
stating plainly: production art has to be generatable from a design record on a
machine with no browser and no Node — a queue worker, a CI step, someone's
laptop with a JSON file on it. Shelling out to a headless Chrome to find out
where a mouth goes is not a pipeline, it is a liability.

The cost of a second copy is drift, and that is paid for by
``tests/test_face.py``, which checks this module against a fixture generated by
the real TypeScript (``tests/production-fixtures.test.ts``). Change a curve on
either side and the other side goes red.

Everything here is pure: params in, primitives out. Face space is a 200x200
box, centre (100,100), exactly as in the TypeScript.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from typing import Any, Iterable, Literal, Sequence

from .jsnum import fmt, js_num, js_round

FACE_BOX = 200
FACE_CX = 100.0
FACE_CY = 100.0

#: Mono-line weight, matched to Grinline so type and faces print as one system.
STROKE = 10.0

#: Past this gap the remaining sliver reads as a smudge, so we draw nothing.
NO_OUTLINE_AT = 340.0

RAD = math.pi / 180.0

EyeShape = Literal["bar", "tick", "round", "arc", "cross", "line", "spiral"]
Mark = Literal["tear", "sweat", "blush", "static", "zzz", "sparkle", "wink"]
#: How the line is drawn. Chalk is the house look; clean is a flat vector.
Finish = Literal["clean", "chalk"]

EYE_SHAPES: tuple[str, ...] = (
    "bar",
    "tick",
    "round",
    "arc",
    "cross",
    "line",
    "spiral",
    "heart",
    "lash",
    "star",
)
MARKS: tuple[str, ...] = (
    "tear",
    "sweat",
    "blush",
    "static",
    "zzz",
    "sparkle",
    "wink",
    "tongue",
    "shades",
    "teeth",
    "bawling",
)

#: The one source of truth for what a parameter is allowed to be. Mirrors
#: ``FACE_LIMITS`` in face.ts, and the fixture test asserts they are the same
#: numbers rather than trusting this comment.
FACE_LIMITS: dict[str, tuple[float, float]] = {
    "width": (52, 88),
    "height": (52, 88),
    "squish": (-18, 18),
    "tilt": (-14, 14),
    "gap": (0, 360),
    "eyeX": (14, 48),
    "eyeY": (52, 104),
    "eyeSize": (5, 26),
    "eyeSquint": (0, 1),
    "eyeTilt": (-40, 40),
    "browY": (26, 74),
    "browAngle": (-40, 40),
    "browLength": (12, 38),
    "mouthY": (104, 168),
    "mouthWidth": (24, 104),
    "mouthCurve": (-1, 1),
    "mouthOpen": (0, 1),
    "mouthWave": (0, 1),
    "mouthFlick": (0, 1),
}


# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Eyes:
    shape: str = "bar"
    x: float = 28
    y: float = 82
    size: float = 13
    squint: float = 0
    tilt: float = 0


@dataclass(frozen=True)
class Brows:
    on: bool = False
    y: float = 52
    angle: float = 0
    length: float = 24


@dataclass(frozen=True)
class Mouth:
    y: float = 128
    width: float = 62
    curve: float = 0.5
    open: float = 0
    wave: float = 0
    flick: float = 0


@dataclass(frozen=True)
class FaceParams:
    width: float = 72
    height: float = 72
    squish: float = 0
    tilt: float = 0
    #: The open loop, in degrees. 360 leaves no outline at all — which is the
    #: default, because that is how these faces get drawn by hand.
    gap: float = 360
    eyes: Eyes = field(default_factory=Eyes)
    brows: Brows = field(default_factory=Brows)
    mouth: Mouth = field(default_factory=Mouth)
    marks: tuple[str, ...] = ()

    @staticmethod
    def from_dict(raw: dict[str, Any] | None) -> "FaceParams":
        raw = raw or {}
        base = FaceParams()
        eyes = dict(raw.get("eyes") or {})
        brows = dict(raw.get("brows") or {})
        mouth = dict(raw.get("mouth") or {})
        marks = raw.get("marks") or []
        return FaceParams(
            width=_num(raw.get("width"), base.width),
            height=_num(raw.get("height"), base.height),
            squish=_num(raw.get("squish"), base.squish),
            tilt=_num(raw.get("tilt"), base.tilt),
            gap=_num(raw.get("gap"), base.gap),
            eyes=Eyes(
                shape=eyes.get("shape") if eyes.get("shape") in EYE_SHAPES else base.eyes.shape,
                x=_num(eyes.get("x"), base.eyes.x),
                y=_num(eyes.get("y"), base.eyes.y),
                size=_num(eyes.get("size"), base.eyes.size),
                squint=_num(eyes.get("squint"), base.eyes.squint),
                tilt=_num(eyes.get("tilt"), base.eyes.tilt),
            ),
            brows=Brows(
                on=bool(brows.get("on", base.brows.on)),
                y=_num(brows.get("y"), base.brows.y),
                angle=_num(brows.get("angle"), base.brows.angle),
                length=_num(brows.get("length"), base.brows.length),
            ),
            mouth=Mouth(
                y=_num(mouth.get("y"), base.mouth.y),
                width=_num(mouth.get("width"), base.mouth.width),
                curve=_num(mouth.get("curve"), base.mouth.curve),
                open=_num(mouth.get("open"), base.mouth.open),
                wave=_num(mouth.get("wave"), base.mouth.wave),
                flick=_num(mouth.get("flick"), base.mouth.flick),
            ),
            marks=tuple(m for m in marks if m in MARKS),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "width": self.width,
            "height": self.height,
            "squish": self.squish,
            "tilt": self.tilt,
            "gap": self.gap,
            "eyes": {
                "shape": self.eyes.shape,
                "x": self.eyes.x,
                "y": self.eyes.y,
                "size": self.eyes.size,
                "squint": self.eyes.squint,
                "tilt": self.eyes.tilt,
            },
            "brows": {
                "on": self.brows.on,
                "y": self.brows.y,
                "angle": self.brows.angle,
                "length": self.brows.length,
            },
            "mouth": {
                "y": self.mouth.y,
                "width": self.mouth.width,
                "curve": self.mouth.curve,
                "open": self.mouth.open,
                "wave": self.mouth.wave,
                "flick": self.mouth.flick,
            },
            "marks": list(self.marks),
        }


def _num(value: Any, fallback: float) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return float(fallback)
    if math.isnan(value) or math.isinf(value):
        return float(value)
    return float(value)


def clamp(value: float, limits: Sequence[float]) -> float:
    lo, hi = limits[0], limits[1]
    if math.isnan(value) or math.isinf(value):
        # face.ts uses Number.isFinite, so a non-finite value collapses to the
        # low end rather than clamping to the high one.
        return float(lo)
    return float(min(hi, max(lo, value)))


def clamp_to(key: str, value: float) -> float:
    return clamp(value, FACE_LIMITS[key])


def clamp_face(p: FaceParams) -> FaceParams:
    """Sanitise a whole face. A face can be ugly on purpose; never broken."""
    seen: list[str] = []
    for m in p.marks:  # dedupe, order-preserving, like `new Set`
        if m not in seen:
            seen.append(m)
    return replace(
        p,
        width=clamp_to("width", p.width),
        height=clamp_to("height", p.height),
        squish=clamp_to("squish", p.squish),
        tilt=clamp_to("tilt", p.tilt),
        gap=clamp_to("gap", p.gap),
        eyes=replace(
            p.eyes,
            x=clamp_to("eyeX", p.eyes.x),
            y=clamp_to("eyeY", p.eyes.y),
            size=clamp_to("eyeSize", p.eyes.size),
            squint=clamp_to("eyeSquint", p.eyes.squint),
            tilt=clamp_to("eyeTilt", p.eyes.tilt),
        ),
        brows=replace(
            p.brows,
            y=clamp_to("browY", p.brows.y),
            angle=clamp_to("browAngle", p.brows.angle),
            length=clamp_to("browLength", p.brows.length),
        ),
        mouth=replace(
            p.mouth,
            y=clamp_to("mouthY", p.mouth.y),
            width=clamp_to("mouthWidth", p.mouth.width),
            curve=clamp_to("mouthCurve", p.mouth.curve),
            open=clamp_to("mouthOpen", p.mouth.open),
            wave=clamp_to("mouthWave", p.mouth.wave),
            flick=clamp_to("mouthFlick", p.mouth.flick),
        ),
        marks=tuple(seen),
    )


# ---------------------------------------------------------------------------
# Drawing primitives
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Prim:
    """One drawable. ``stroke`` and ``fill`` carry SVG path data; ``dot`` is an
    ellipse, which is cheaper to state than to describe as arcs."""

    kind: str  # 'stroke' | 'fill' | 'dot'
    key: str
    d: str = ""
    w: float | None = None
    opacity: float | None = None
    cx: float = 0
    cy: float = 0
    rx: float = 0
    ry: float = 0


Pt = tuple[float, float]


def smooth(points: Sequence[Pt], closed: bool = False) -> str:
    """Catmull-Rom through the points, emitted as cubics.

    Sampling a curve into a polyline and stroking it looks faceted at print
    size, which is exactly the size this art is used at.
    """
    if len(points) < 2:
        return ""

    def pt(i: int) -> Pt:
        if closed:
            return points[(i + len(points)) % len(points)]
        return points[min(len(points) - 1, max(0, i))]

    d = f"M{fmt(points[0][0])},{fmt(points[0][1])}"
    last = len(points) if closed else len(points) - 1
    for i in range(last):
        p0, p1, p2, p3 = pt(i - 1), pt(i), pt(i + 1), pt(i + 2)
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        d += (
            f"C{fmt(c1[0])},{fmt(c1[1])} "
            f"{fmt(c2[0])},{fmt(c2[1])} "
            f"{fmt(p2[0])},{fmt(p2[1])}"
        )
    return f"{d}Z" if closed else d


def _signed_pow(value: float, exponent: float) -> float:
    """``Math.sign(v) * Math.abs(v) ** e``."""
    magnitude = abs(value) ** exponent
    if value > 0:
        return magnitude
    if value < 0:
        return -magnitude
    return 0.0


# ---------------------------------------------------------------------------
# The hand-drawn wobble
# ---------------------------------------------------------------------------

# Chalk finish gets a small, stable jitter baked into the geometry itself —
# not applied as a screen filter — so the same "drawn by hand, not plotted"
# quality shows up everywhere a face is used: the flat SVG proof, the 3D
# texture, the photo mockup, and this module's own print file. Ported from the
# wobble block in face.ts, function for function; the fixture test checks it
# path string for path string, chalk finish included.
#
# Trig-based rather than a bitwise hash, and for the same reason it is in the
# TypeScript: both sides round every coordinate to two decimal places before
# it reaches a path string, and math.sin/Math.sin agree to far more precision
# than that survives — so the same face and the same named point wobble to the
# same numbers on both sides, with no 32-bit-integer overflow behaviour to
# reproduce exactly across languages.


@dataclass(frozen=True)
class Wob:
    seed: float
    on: bool


NO_WOB = Wob(seed=0, on=False)


def _seed_of(text: str) -> float:
    """A small, stable seed for a short string."""
    h = 0
    for ch in text:
        h = (h * 131 + ord(ch)) % 1000003
    return h


def _noise01(seed: float, salt: float) -> float:
    """A stable pseudo-random unit value in [0,1) for a (seed, salt) pair."""
    x = math.sin(seed * 12.9898 + salt * 78.233 + 37.719) * 43758.5453
    return x - math.floor(x)


def _wob(W: Wob, key: str, amount: float) -> Pt:
    """A small, stable 2D offset for one named point on one face. Zero when off."""
    if not W.on or amount <= 0:
        return (0.0, 0.0)
    salt = _seed_of(key)
    return (
        (_noise01(W.seed, salt * 2 + 1) * 2 - 1) * amount,
        (_noise01(W.seed, salt * 2 + 2) * 2 - 1) * amount,
    )


def _radius_jitter(W: Wob, key: str, amount: float) -> float:
    """A multiplier close to 1, for radii and widths that should not all match exactly."""
    if not W.on or amount <= 0:
        return 1.0
    return 1 + (_noise01(W.seed, _seed_of(key)) - 0.5) * 2 * amount


def _bow(W: Wob, key: str, t: float, amount: float, ripple_weight: float = 0.4) -> float:
    """A gentle bow along a parameter t in [0,1]. One slow wave carries the
    shape; a quieter, faster ripple rides on top, trimmed back by
    ``ripple_weight`` for short strokes where it would otherwise zigzag."""
    if not W.on or amount <= 0:
        return 0.0
    salt = _seed_of(key)
    f1 = 1 + math.floor(_noise01(W.seed, salt * 2 + 3) * 2)  # 1 or 2 slow waves
    f2 = 3 + math.floor(_noise01(W.seed, salt * 2 + 4) * 2)  # a faster ripple riding on top
    p1 = _noise01(W.seed, salt * 2 + 5) * math.pi * 2
    p2 = _noise01(W.seed, salt * 2 + 6) * math.pi * 2
    return amount * (
        math.sin(t * math.pi * 2 * f1 + p1) + ripple_weight * math.sin(t * math.pi * 2 * f2 + p2)
    )


#: How far the chalk finish is allowed to nudge a point, in face units.
WOBBLE_BOW = 2.6
WOBBLE_POINT = 1.5
WOBBLE_RADIUS = 0.16


def outline_path(p: FaceParams, W: Wob = NO_WOB) -> str:
    """A superellipse, drawn from the far side of the open loop round to the
    near side, so the gap is simply the part we never draw."""
    if p.gap >= NO_OUTLINE_AT:
        return ""
    n = 3.4  # squircle exponent
    gap_centre = 315  # top right
    half = p.gap / 2
    start = gap_centre + half
    end = gap_centre + 360 - half
    steps = 72
    pts: list[Pt] = []
    for i in range(steps + 1):
        deg = start + (end - start) * i / steps
        t = deg * RAD
        ct = math.cos(t)
        st = math.sin(t)
        # The pull: crown and chin move in opposite directions, so dragging the
        # top of the face stretches it like putty instead of just scaling it.
        ry = p.height + (p.squish if st < 0 else -p.squish)
        x = FACE_CX + p.width * _signed_pow(ct, 2 / n)
        y = FACE_CY + ry * _signed_pow(st, 2 / n)
        # A hand tracing a squircle wanders in and out along its own radius,
        # not sideways across it — pushing along (ct, st) keeps the wobble
        # from folding the curve back on itself at the corners.
        b = _bow(W, "outline", i / steps, WOBBLE_BOW)
        pts.append((x + b * ct, y + b * st))
    return smooth(pts, p.gap <= 0.5)


def _eye_prims(p: FaceParams, side: int, W: Wob = NO_WOB) -> list[Prim]:
    cx = FACE_CX + side * p.eyes.x
    cy = p.eyes.y
    s = p.eyes.size
    open_ = 1 - 0.88 * p.eyes.squint
    key = "eyeL" if side < 0 else "eyeR"
    prims: list[Prim] = []

    if p.eyes.shape == "round":
        dx, dy = _wob(W, f"{key}c", WOBBLE_POINT * 0.6)
        rj = _radius_jitter(W, f"{key}r", WOBBLE_RADIUS)
        prims.append(
            Prim(
                kind="dot",
                cx=cx + dx,
                cy=cy + dy,
                rx=s * 0.62 * rj,
                ry=(s * 0.62 * open_ + 0.6) * rj,
                key=key,
            )
        )
    elif p.eyes.shape == "bar":
        h = s * 1.5 * open_
        ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT)
        bx, by = _wob(W, f"{key}p1", WOBBLE_POINT)
        prims.append(
            Prim(
                kind="stroke",
                d=f"M{fmt(cx + ax)},{fmt(cy - h / 2 + ay)} L{fmt(cx + bx)},{fmt(cy + h / 2 + by)}",
                w=s * 0.95,
                key=key,
            )
        )
    elif p.eyes.shape == "tick":
        # The eye as a single flicked stroke.
        h = s * 1.35 * open_
        lean = s * 0.28
        ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT)
        bx, by = _wob(W, f"{key}p1", WOBBLE_POINT)
        prims.append(
            Prim(
                kind="stroke",
                d=(
                    f"M{fmt(cx - side * lean + ax)},{fmt(cy - h / 2 + ay)} "
                    f"L{fmt(cx + side * lean + bx)},{fmt(cy + h / 2 + by)}"
                ),
                w=STROKE * 0.95,
                key=key,
            )
        )
    elif p.eyes.shape == "arc":
        # The happy squint.
        w = s * 1.35
        lift = s * (0.75 + 0.5 * open_)
        ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT)
        qx, qy = _wob(W, f"{key}pq", WOBBLE_POINT)
        bx, by = _wob(W, f"{key}p1", WOBBLE_POINT)
        prims.append(
            Prim(
                kind="stroke",
                d=(
                    f"M{fmt(cx - w + ax)},{fmt(cy + lift * 0.35 + ay)} "
                    f"Q{fmt(cx + qx)},{fmt(cy - lift + qy)} "
                    f"{fmt(cx + w + bx)},{fmt(cy + lift * 0.35 + by)}"
                ),
                key=key,
            )
        )
    elif p.eyes.shape == "lash":
        # The laughing/flirty eye: the same closed-eye arc as `arc`, with two
        # short flicks fanned off the outer corner — the detail that turns a
        # plain closed eye into an eyelash doodle.
        w = s * 1.3
        lift = s * (0.62 + 0.42 * open_)
        ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT)
        qx, qy = _wob(W, f"{key}pq", WOBBLE_POINT)
        bx, by = _wob(W, f"{key}p1", WOBBLE_POINT)
        corner_x = cx + side * w
        corner_y = cy + lift * 0.3
        prims.append(
            Prim(
                kind="stroke",
                d=(
                    f"M{fmt(cx - w + ax)},{fmt(cy + lift * 0.3 + ay)} "
                    f"Q{fmt(cx + qx)},{fmt(cy - lift + qy)} "
                    f"{fmt(cx + w + bx)},{fmt(cy + lift * 0.3 + by)}"
                ),
                key=key,
            )
        )
        lashes = [(0.98, -0.22, 0.62), (0.45, -0.9, 0.6)]
        for i, (ux, uy, scale) in enumerate(lashes):
            length = s * scale
            lx, ly = _wob(W, f"{key}L{i}", WOBBLE_POINT * 0.6)
            prims.append(
                Prim(
                    kind="stroke",
                    d=(
                        f"M{fmt(corner_x + lx)},{fmt(corner_y + ly)} "
                        f"L{fmt(corner_x + side * ux * length + lx)},{fmt(corner_y + uy * length + ly)}"
                    ),
                    w=STROKE * 0.55,
                    key=f"{key}L{i}",
                )
            )
    elif p.eyes.shape == "line":
        w = s * 1.4
        ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT)
        bx, by = _wob(W, f"{key}p1", WOBBLE_POINT)
        prims.append(
            Prim(
                kind="stroke",
                d=f"M{fmt(cx - w + ax)},{fmt(cy + ay)} L{fmt(cx + w + bx)},{fmt(cy + by)}",
                key=key,
            )
        )
    elif p.eyes.shape == "cross":
        w = s * 1.05
        ax, ay = _wob(W, f"{key}ap0", WOBBLE_POINT)
        bx, by = _wob(W, f"{key}ap1", WOBBLE_POINT)
        cx2, cy2 = _wob(W, f"{key}bp0", WOBBLE_POINT)
        dx2, dy2 = _wob(W, f"{key}bp1", WOBBLE_POINT)
        prims.append(
            Prim(
                kind="stroke",
                d=f"M{fmt(cx - w + ax)},{fmt(cy - w + ay)} L{fmt(cx + w + bx)},{fmt(cy + w + by)}",
                key=f"{key}a",
            )
        )
        prims.append(
            Prim(
                kind="stroke",
                d=f"M{fmt(cx + w + cx2)},{fmt(cy - w + cy2)} L{fmt(cx - w + dx2)},{fmt(cy + w + dy2)}",
                key=f"{key}b",
            )
        )
    elif p.eyes.shape == "heart":
        # Two lobes and a point. Filled rather than stroked, because a heart
        # outlined in a 10-unit mono line at cuff-hit size closes up into a blob.
        dx, dy = _wob(W, f"{key}c", WOBBLE_POINT * 0.8)
        wj = _radius_jitter(W, f"{key}w", WOBBLE_RADIUS)
        hj = _radius_jitter(W, f"{key}h", WOBBLE_RADIUS)
        cx2 = cx + dx
        cy2 = cy + dy
        w = s * 0.98 * wj
        h = s * (0.72 + 0.42 * open_) * hj
        prims.append(
            Prim(
                kind="fill",
                d=(
                    f"M{fmt(cx2)},{fmt(cy2 + h * 0.72)} "
                    f"C{fmt(cx2 - w * 1.18)},{fmt(cy2 - h * 0.1)} "
                    f"{fmt(cx2 - w * 0.62)},{fmt(cy2 - h * 1.05)} {fmt(cx2)},{fmt(cy2 - h * 0.3)} "
                    f"C{fmt(cx2 + w * 0.62)},{fmt(cy2 - h * 1.05)} "
                    f"{fmt(cx2 + w * 1.18)},{fmt(cy2 - h * 0.1)} {fmt(cx2)},{fmt(cy2 + h * 0.72)} Z"
                ),
                key=key,
            )
        )
    elif p.eyes.shape == "star":
        # The same four-point twinkle the `sparkle` mark draws, recentred as
        # an eye rather than tied to a face corner — the starstruck look,
        # reusing geometry already proven to read clearly at cuff-hit size
        # rather than inventing a second "star" shape for the brand to carry.
        st = s * 1.05
        dx, dy = _wob(W, f"{key}c", WOBBLE_POINT * 0.6)
        sj = _radius_jitter(W, f"{key}s", WOBBLE_RADIUS)
        cx2 = cx + dx
        cy2 = cy + dy
        sz = st * sj
        prims.append(
            Prim(
                kind="fill",
                d=(
                    f"M{fmt(cx2)},{fmt(cy2 - sz)} Q{fmt(cx2 + 2)},{fmt(cy2 - 2)} {fmt(cx2 + sz)},{fmt(cy2)} "
                    f"Q{fmt(cx2 + 2)},{fmt(cy2 + 2)} {fmt(cx2)},{fmt(cy2 + sz)} "
                    f"Q{fmt(cx2 - 2)},{fmt(cy2 + 2)} {fmt(cx2 - sz)},{fmt(cy2)} "
                    f"Q{fmt(cx2 - 2)},{fmt(cy2 - 2)} {fmt(cx2)},{fmt(cy2 - sz)} Z"
                ),
                key=key,
            )
        )
    elif p.eyes.shape == "spiral":
        # Two and a bit turns — the "I am not really here" eye.
        turns = 2.25
        dx, dy = _wob(W, f"{key}c", WOBBLE_POINT * 0.5)
        pts: list[Pt] = []
        steps = 26
        for i in range(steps + 1):
            t = (i / steps) * turns * 2 * math.pi
            rad = (s * 1.1 * i) / steps
            pts.append((cx + dx + rad * math.cos(t), cy + dy + rad * math.sin(t)))
        prims.append(Prim(kind="stroke", d=smooth(pts), w=STROKE * 0.7, key=key))
    return prims


def _wink_prim(p: FaceParams, side: int, W: Wob = NO_WOB) -> Prim:
    """A shut eye: the lid as one arc."""
    cx = FACE_CX + side * p.eyes.x
    cy = p.eyes.y
    w = p.eyes.size * 1.25
    key = "eyeL" if side < 0 else "eyeR"
    ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT)
    qx, qy = _wob(W, f"{key}pq", WOBBLE_POINT)
    bx, by = _wob(W, f"{key}p1", WOBBLE_POINT)
    return Prim(
        kind="stroke",
        d=(
            f"M{fmt(cx - w + ax)},{fmt(cy + 2 + ay)} "
            f"Q{fmt(cx + qx)},{fmt(cy - p.eyes.size * 1.15 + qy)} "
            f"{fmt(cx + w + bx)},{fmt(cy + 2 + by)}"
        ),
        key=key,
    )


def _brow_prim(p: FaceParams, side: int, W: Wob = NO_WOB) -> Prim:
    cx = FACE_CX + side * p.eyes.x
    half = p.brows.length / 2
    key = "browL" if side < 0 else "browR"
    # Positive angle drops the inner end. Mirrored so both brows read the same.
    rise = math.tan(p.brows.angle * RAD) * half
    inner = (cx + side * -half, p.brows.y + rise)
    outer = (cx + side * half, p.brows.y - rise)
    ix, iy = _wob(W, f"{key}p0", WOBBLE_POINT)
    ox, oy = _wob(W, f"{key}p1", WOBBLE_POINT)
    return Prim(
        kind="stroke",
        d=f"M{fmt(inner[0] + ix)},{fmt(inner[1] + iy)} L{fmt(outer[0] + ox)},{fmt(outer[1] + oy)}",
        key=key,
    )


def _mouth_points(p: FaceParams, lip_offset: float, W: Wob, key: str) -> list[Pt]:
    half = p.mouth.width / 2
    steps = 18
    # bow()'s two harmonics complete their cycles over t=0..1 regardless of
    # how physically wide the stroke is, so the same amplitude that reads as a
    # gentle bend on the outline's long loop reads as a jagged zigzag on a
    # short, flat mouth. Scaling by width against a mid-range reference (most
    # mouths run 46-74 units) keeps the wobble a fraction of the mouth rather
    # than a fixed absolute nudge.
    mouth_wobble = WOBBLE_BOW * min(1.15, max(0.32, p.mouth.width / 78))
    pts: list[Pt] = []
    for i in range(steps + 1):
        t = i / steps
        x = FACE_CX - half + p.mouth.width * t
        # Parabola through the ends: 0 at both, 1 in the middle.
        curve_shape = 4 * t * (1 - t)
        wave = math.sin(t * math.pi * 3) * 7 * p.mouth.wave * (0.35 + curve_shape)
        hand = _bow(W, key, t, mouth_wobble, 0.2)
        pts.append((x, p.mouth.y + curve_shape * p.mouth.curve * 30 + wave + lip_offset * curve_shape + hand))
    return pts


def mouth_prims(p: FaceParams, W: Wob = NO_WOB) -> list[Prim]:
    if p.mouth.open > 0.02:
        # Open mouth: the line becomes the upper lip and a mirrored lower lip
        # closes the shape, so "open" reads as a hole rather than a thick
        # line. The two lips get their own wobble key so they don't bow in
        # lockstep.
        upper = _mouth_points(p, 0, W, "mouth")
        lower = list(reversed(_mouth_points(p, 14 + p.mouth.open * 46, W, "mouthLower")))
        lower_d = smooth(lower)
        if lower_d.startswith("M"):
            lower_d = "L" + lower_d[1:]
        return [Prim(kind="fill", d=f"{smooth(upper)} {lower_d} Z", key="mouth")]

    pts = _mouth_points(p, 0, W, "mouth")
    d = smooth(pts)
    if p.mouth.flick > 0.01:
        # Carry the stroke past the corner and upwards, the way a pen leaves
        # the paper.
        ex, ey = pts[-1]
        d += f" L{fmt(ex + p.mouth.flick * 11)},{fmt(ey - p.mouth.flick * 17)}"
    return [Prim(kind="stroke", d=d, key="mouth")]


def _mark_prims(p: FaceParams, W: Wob = NO_WOB) -> list[Prim]:
    out: list[Prim] = []
    eye_l = FACE_CX - p.eyes.x
    eye_r = FACE_CX + p.eyes.x

    # Marks hang off the rim of the face — but with no outline there is no rim,
    # and a sweat drop parked where the edge used to be just floats in space.
    bare = p.gap >= NO_OUTLINE_AT
    span_x = (
        min(p.width, max(p.eyes.x + p.eyes.size, p.mouth.width / 2) + 12) if bare else p.width
    )
    span_y = (
        min(p.height, max(p.mouth.y - FACE_CY, FACE_CY - p.eyes.y + p.eyes.size) + 10)
        if bare
        else p.height
    )

    for mark in p.marks:
        if mark == "tear":
            dx, dy = _wob(W, "tear", WOBBLE_POINT * 0.7)
            x = eye_l + dx
            y = p.eyes.y + p.eyes.size + 12 + dy
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(x)},{fmt(y)} "
                        f"C{fmt(x + 9)},{fmt(y + 12)} {fmt(x + 8)},{fmt(y + 26)} {fmt(x)},{fmt(y + 26)} "
                        f"C{fmt(x - 8)},{fmt(y + 26)} {fmt(x - 9)},{fmt(y + 12)} {fmt(x)},{fmt(y)} Z"
                    ),
                    key="tear",
                )
            )
        elif mark == "bawling":
            # The full-on cry: a streaming tear under both eyes, not one
            # small drop under one — `tear` stays the quiet version, this is
            # the loud one.
            for side, drop_key in ((-1, "bawlingL"), (1, "bawlingR")):
                dx, dy = _wob(W, drop_key, WOBBLE_POINT * 0.6)
                x = (eye_l if side < 0 else eye_r) + dx
                y = p.eyes.y + p.eyes.size + 12 + dy
                out.append(
                    Prim(
                        kind="fill",
                        d=(
                            f"M{fmt(x)},{fmt(y)} "
                            f"C{fmt(x + 10)},{fmt(y + 16)} {fmt(x + 9)},{fmt(y + 38)} {fmt(x)},{fmt(y + 38)} "
                            f"C{fmt(x - 9)},{fmt(y + 38)} {fmt(x - 10)},{fmt(y + 16)} {fmt(x)},{fmt(y)} Z"
                        ),
                        key=drop_key,
                    )
                )
        elif mark == "sweat":
            dx, dy = _wob(W, "sweat", WOBBLE_POINT * 0.7)
            x = FACE_CX + span_x * 0.72 + dx
            y = FACE_CY - span_y * 0.52 + dy
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(x)},{fmt(y)} "
                        f"C{fmt(x + 8)},{fmt(y + 10)} {fmt(x + 7)},{fmt(y + 22)} {fmt(x)},{fmt(y + 22)} "
                        f"C{fmt(x - 7)},{fmt(y + 22)} {fmt(x - 8)},{fmt(y + 10)} {fmt(x)},{fmt(y)} Z"
                    ),
                    key="sweat",
                )
            )
        elif mark == "blush":
            y = p.eyes.y + p.eyes.size + 20
            lx, ly = _wob(W, "blushL", WOBBLE_POINT * 0.5)
            rx, ry = _wob(W, "blushR", WOBBLE_POINT * 0.5)
            lj = _radius_jitter(W, "blushLr", WOBBLE_RADIUS)
            rj = _radius_jitter(W, "blushRr", WOBBLE_RADIUS)
            out.append(
                Prim(
                    kind="dot",
                    cx=eye_l - 6 + lx,
                    cy=y + ly,
                    rx=13 * lj,
                    ry=7 * lj,
                    opacity=0.5,
                    key="blushL",
                )
            )
            out.append(
                Prim(
                    kind="dot",
                    cx=eye_r + 6 + rx,
                    cy=y + ry,
                    rx=13 * rj,
                    ry=7 * rj,
                    opacity=0.5,
                    key="blushR",
                )
            )
        elif mark == "static":
            # Interference across the face — the overwhelmed look.
            for i in range(3):
                y = FACE_CY - 18 + i * 26
                w = span_x * (0.82 if i == 1 else 0.6)
                key = f"static{i}"
                ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT * 0.6)
                bx, by = _wob(W, f"{key}p1", WOBBLE_POINT * 0.6)
                out.append(
                    Prim(
                        kind="stroke",
                        d=f"M{fmt(FACE_CX - w + ax)},{fmt(y + ay)} L{fmt(FACE_CX + w + bx)},{fmt(y + by)}",
                        w=STROKE * 0.55,
                        opacity=0.55,
                        key=key,
                    )
                )
        elif mark == "zzz":
            base = FACE_CX + span_x * 0.62
            top = FACE_CY - span_y * 0.72
            for i in range(3):
                s = 9 + i * 5
                x = base + i * 5
                y = top - i * 20
                key = f"z{i}"
                ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT * 0.6)
                bx, by = _wob(W, f"{key}p1", WOBBLE_POINT * 0.6)
                cx, cy = _wob(W, f"{key}p2", WOBBLE_POINT * 0.6)
                dxp, dyp = _wob(W, f"{key}p3", WOBBLE_POINT * 0.6)
                out.append(
                    Prim(
                        kind="stroke",
                        d=(
                            f"M{fmt(x - s + ax)},{fmt(y - s + ay)} L{fmt(x + s + bx)},{fmt(y - s + by)} "
                            f"L{fmt(x - s + cx)},{fmt(y + s + cy)} L{fmt(x + s + dxp)},{fmt(y + s + dyp)}"
                        ),
                        w=STROKE * 0.6,
                        key=key,
                    )
                )
        elif mark == "tongue":
            # Hung from the middle of the mouth, which is where the mouth's own
            # bow peaks — so it follows a grin up and a grimace down instead of
            # floating at a fixed height.
            mid_y = p.mouth.y + p.mouth.curve * 30
            # Narrow and deep. Wider than this and it stops reading as a tongue
            # and starts reading as a chin — it has to clear the 10-unit mouth
            # stroke it hangs off by enough to be a separate shape.
            w = min(13, p.mouth.width * 0.2)
            drop = w * 2.4
            dx, dy = _wob(W, "tongue", WOBBLE_POINT * 0.6)
            wj = _radius_jitter(W, "tonguew", WOBBLE_RADIUS)
            cx = FACE_CX + dx
            w2 = w * wj
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(cx - w2)},{fmt(mid_y - 1 + dy)} "
                        f"C{fmt(cx - w2)},{fmt(mid_y + drop + dy)} "
                        f"{fmt(cx + w2)},{fmt(mid_y + drop + dy)} {fmt(cx + w2)},{fmt(mid_y - 1 + dy)} Z"
                    ),
                    key="tongue",
                )
            )
        elif mark == "teeth":
            # A few short dividers across the mouth's own curve — a jagged
            # bite rather than a second mouth shape. The same convention a
            # hand-drawn doodle uses for a gritted grin, an angry snarl or a
            # scared chatter, depending on what the brows around it are
            # doing.
            mid_y = p.mouth.y + p.mouth.curve * 30
            half = min(p.mouth.width * 0.4, 30)
            count = 4
            for i in range(count):
                t = (i + 0.5) / count
                x = FACE_CX - half + half * 2 * t
                key = f"teeth{i}"
                ax, ay = _wob(W, f"{key}p0", WOBBLE_POINT * 0.5)
                bx, by = _wob(W, f"{key}p1", WOBBLE_POINT * 0.5)
                out.append(
                    Prim(
                        kind="stroke",
                        d=f"M{fmt(x + ax)},{fmt(mid_y - 7 + ay)} L{fmt(x + bx)},{fmt(mid_y + 7 + by)}",
                        w=STROKE * 0.55,
                        key=key,
                    )
                )
        elif mark == "sparkle":
            dx, dy = _wob(W, "sparkle", WOBBLE_POINT * 0.6)
            x = FACE_CX + span_x * 0.74 + dx
            y = FACE_CY - span_y * 0.62 + dy
            s = 14
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(x)},{fmt(y - s)} Q{fmt(x + 2)},{fmt(y - 2)} {fmt(x + s)},{fmt(y)} "
                        f"Q{fmt(x + 2)},{fmt(y + 2)} {fmt(x)},{fmt(y + s)} "
                        f"Q{fmt(x - 2)},{fmt(y + 2)} {fmt(x - s)},{fmt(y)} "
                        f"Q{fmt(x - 2)},{fmt(y - 2)} {fmt(x)},{fmt(y - s)} Z"
                    ),
                    key="sparkle",
                )
            )
        elif mark == "shades":
            # A single bar over both eyes — filled, so it simply sits on top
            # of whatever eye shape is underneath rather than needing one.
            # Lens radius follows eye size, so bigger eyes get bigger lenses
            # instead of a mismatched fit. Each lens is a proper four-bezier
            # rounded square (the circle-to-bezier kappa constant) — a
            # two-bezier approximation pinches into a flattened lozenge
            # instead of reading as a lens.
            kappa = 0.5522847498307936
            dx, dy = _wob(W, "shades", WOBBLE_POINT * 0.5)
            rj = _radius_jitter(W, "shadesr", WOBBLE_RADIUS)
            y = p.eyes.y + dy
            rx = p.eyes.size * 1.05 * rj
            ry = p.eyes.size * 1.15 * rj
            ox = rx * kappa
            oy = ry * kappa
            bridge_h = ry * 0.5

            def lens(lcx: float) -> str:
                cx2 = lcx + dx
                return (
                    f"M{fmt(cx2 - rx)},{fmt(y)} "
                    f"C{fmt(cx2 - rx)},{fmt(y - oy)} {fmt(cx2 - ox)},{fmt(y - ry)} {fmt(cx2)},{fmt(y - ry)} "
                    f"C{fmt(cx2 + ox)},{fmt(y - ry)} {fmt(cx2 + rx)},{fmt(y - oy)} {fmt(cx2 + rx)},{fmt(y)} "
                    f"C{fmt(cx2 + rx)},{fmt(y + oy)} {fmt(cx2 + ox)},{fmt(y + ry)} {fmt(cx2)},{fmt(y + ry)} "
                    f"C{fmt(cx2 - ox)},{fmt(y + ry)} {fmt(cx2 - rx)},{fmt(y + oy)} {fmt(cx2 - rx)},{fmt(y)} Z"
                )

            # The bridge overlaps a little into each lens rather than butting
            # against it exactly, so there is no hairline gap at the seam.
            bridge_left = eye_l + rx * 0.55 + dx
            bridge_right = eye_r - rx * 0.55 + dx
            bridge = (
                (
                    f"M{fmt(bridge_left)},{fmt(y - bridge_h / 2)} L{fmt(bridge_right)},{fmt(y - bridge_h / 2)} "
                    f"L{fmt(bridge_right)},{fmt(y + bridge_h / 2)} L{fmt(bridge_left)},{fmt(y + bridge_h / 2)} Z"
                )
                if bridge_right > bridge_left
                else ""
            )
            out.append(
                Prim(kind="fill", d=f"{lens(eye_l)} {lens(eye_r)} {bridge}", key="shades")
            )
    return out


@dataclass(frozen=True)
class Spin:
    """A rotation about a point, in the form every renderer can use."""

    deg: float
    cx: float
    cy: float


@dataclass(frozen=True)
class FaceGeometry:
    tilt: float
    outline: Prim | None
    eyes_left: list[Prim]
    eyes_right: list[Prim]
    eye_rotation: tuple[Spin, Spin]  # left, right
    rest: list[Prim]

    def all_prims(self) -> Iterable[Prim]:
        if self.outline:
            yield self.outline
        yield from self.eyes_left
        yield from self.eyes_right
        yield from self.rest


def face_signature(p: FaceParams) -> str:
    """Stable-ish identity for a face — ported from ``faceSignature`` in
    face.ts. It is what the chalk wobble seeds itself from, so it has to
    produce the byte-identical string TypeScript does for the same face:
    a differently-formatted number here reseeds every wobbled coordinate on
    both sides, not just this one."""
    f = clamp_face(p)
    values: list[Any] = [
        f.width, f.height, f.squish, f.tilt, f.gap,
        f.eyes.shape, f.eyes.x, f.eyes.y, f.eyes.size, f.eyes.squint, f.eyes.tilt,
        1 if f.brows.on else 0, f.brows.y, f.brows.angle, f.brows.length,
        f.mouth.y, f.mouth.width, f.mouth.curve, f.mouth.open, f.mouth.wave, f.mouth.flick,
        ".".join(sorted(f.marks)),
    ]
    parts = []
    for v in values:
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            parts.append(js_num(js_round(v * 10) / 10))
        else:
            parts.append(str(v))
    return "|".join(parts)


def build_face(raw: FaceParams, finish: Finish = "clean") -> FaceGeometry:
    p = clamp_face(raw)
    # The wobble is keyed off the whole face, not off each primitive alone, so
    # the same face always wobbles the same way — a re-render, a second
    # surface (the 3D texture, this print file) or a second visit all draw the
    # identical "hand".
    W = Wob(seed=_seed_of(face_signature(p)), on=True) if finish == "chalk" else NO_WOB
    outline_d = outline_path(p, W)
    return FaceGeometry(
        tilt=p.tilt,
        outline=Prim(kind="stroke", d=outline_d, key="outline") if outline_d else None,
        # A wink is the one asymmetry the face allows: eyes are otherwise always
        # mirrored, because independent eyes read as a bug rather than a choice.
        eyes_left=[_wink_prim(p, -1, W)] if "wink" in p.marks else _eye_prims(p, -1, W),
        eyes_right=_eye_prims(p, 1, W),
        eye_rotation=(
            Spin(deg=-p.eyes.tilt, cx=FACE_CX - p.eyes.x, cy=p.eyes.y),
            Spin(deg=p.eyes.tilt, cx=FACE_CX + p.eyes.x, cy=p.eyes.y),
        ),
        rest=[
            *([_brow_prim(p, -1, W), _brow_prim(p, 1, W)] if p.brows.on else []),
            *mouth_prims(p, W),
            *_mark_prims(p, W),
        ],
    )
