"""
The face engine, ported from ``src/brand/face.ts``.

This is a deliberate second copy of the geometry, and the reason is worth
stating plainly: production art has to be generatable from a design record on a
machine with no browser and no Node — a queue worker, a CI step, someone's
laptop with a JSON file on it. Shelling out to a headless Chrome to find out
where a mouth goes is not a pipeline, it is a liability.

The cost of a second copy is drift, and that is paid for by
``tests/test_face.py``, which checks this module against a fixture generated by
the real TypeScript (``tests/production-fixtures.test.ts``). Change a curve on
either side and the other side goes red.

Everything here is pure: params in, primitives out. Face space is a 200x200
box, centre (100,100), exactly as in the TypeScript.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from typing import Any, Iterable, Literal, Sequence

from .jsnum import fmt

FACE_BOX = 200
FACE_CX = 100.0
FACE_CY = 100.0

#: Mono-line weight, matched to Grinline so type and faces print as one system.
STROKE = 10.0

#: Past this gap the remaining sliver reads as a smudge, so we draw nothing.
NO_OUTLINE_AT = 340.0

RAD = math.pi / 180.0

EyeShape = Literal["bar", "tick", "round", "arc", "cross", "line", "spiral"]
Mark = Literal["tear", "sweat", "blush", "static", "zzz", "sparkle", "wink"]

EYE_SHAPES: tuple[str, ...] = (
    "bar",
    "tick",
    "round",
    "arc",
    "cross",
    "line",
    "spiral",
    "heart",
)
MARKS: tuple[str, ...] = (
    "tear",
    "sweat",
    "blush",
    "static",
    "zzz",
    "sparkle",
    "wink",
    "tongue",
)

#: The one source of truth for what a parameter is allowed to be. Mirrors
#: ``FACE_LIMITS`` in face.ts, and the fixture test asserts they are the same
#: numbers rather than trusting this comment.
FACE_LIMITS: dict[str, tuple[float, float]] = {
    "width": (52, 88),
    "height": (52, 88),
    "squish": (-18, 18),
    "tilt": (-14, 14),
    "gap": (0, 360),
    "eyeX": (14, 48),
    "eyeY": (52, 104),
    "eyeSize": (5, 26),
    "eyeSquint": (0, 1),
    "eyeTilt": (-40, 40),
    "browY": (26, 74),
    "browAngle": (-40, 40),
    "browLength": (12, 38),
    "mouthY": (104, 168),
    "mouthWidth": (24, 104),
    "mouthCurve": (-1, 1),
    "mouthOpen": (0, 1),
    "mouthWave": (0, 1),
    "mouthFlick": (0, 1),
}


# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Eyes:
    shape: str = "bar"
    x: float = 28
    y: float = 82
    size: float = 13
    squint: float = 0
    tilt: float = 0


@dataclass(frozen=True)
class Brows:
    on: bool = False
    y: float = 52
    angle: float = 0
    length: float = 24


@dataclass(frozen=True)
class Mouth:
    y: float = 128
    width: float = 62
    curve: float = 0.5
    open: float = 0
    wave: float = 0
    flick: float = 0


@dataclass(frozen=True)
class FaceParams:
    width: float = 72
    height: float = 72
    squish: float = 0
    tilt: float = 0
    #: The open loop, in degrees. 360 leaves no outline at all — which is the
    #: default, because that is how these faces get drawn by hand.
    gap: float = 360
    eyes: Eyes = field(default_factory=Eyes)
    brows: Brows = field(default_factory=Brows)
    mouth: Mouth = field(default_factory=Mouth)
    marks: tuple[str, ...] = ()

    @staticmethod
    def from_dict(raw: dict[str, Any] | None) -> "FaceParams":
        raw = raw or {}
        base = FaceParams()
        eyes = dict(raw.get("eyes") or {})
        brows = dict(raw.get("brows") or {})
        mouth = dict(raw.get("mouth") or {})
        marks = raw.get("marks") or []
        return FaceParams(
            width=_num(raw.get("width"), base.width),
            height=_num(raw.get("height"), base.height),
            squish=_num(raw.get("squish"), base.squish),
            tilt=_num(raw.get("tilt"), base.tilt),
            gap=_num(raw.get("gap"), base.gap),
            eyes=Eyes(
                shape=eyes.get("shape") if eyes.get("shape") in EYE_SHAPES else base.eyes.shape,
                x=_num(eyes.get("x"), base.eyes.x),
                y=_num(eyes.get("y"), base.eyes.y),
                size=_num(eyes.get("size"), base.eyes.size),
                squint=_num(eyes.get("squint"), base.eyes.squint),
                tilt=_num(eyes.get("tilt"), base.eyes.tilt),
            ),
            brows=Brows(
                on=bool(brows.get("on", base.brows.on)),
                y=_num(brows.get("y"), base.brows.y),
                angle=_num(brows.get("angle"), base.brows.angle),
                length=_num(brows.get("length"), base.brows.length),
            ),
            mouth=Mouth(
                y=_num(mouth.get("y"), base.mouth.y),
                width=_num(mouth.get("width"), base.mouth.width),
                curve=_num(mouth.get("curve"), base.mouth.curve),
                open=_num(mouth.get("open"), base.mouth.open),
                wave=_num(mouth.get("wave"), base.mouth.wave),
                flick=_num(mouth.get("flick"), base.mouth.flick),
            ),
            marks=tuple(m for m in marks if m in MARKS),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "width": self.width,
            "height": self.height,
            "squish": self.squish,
            "tilt": self.tilt,
            "gap": self.gap,
            "eyes": {
                "shape": self.eyes.shape,
                "x": self.eyes.x,
                "y": self.eyes.y,
                "size": self.eyes.size,
                "squint": self.eyes.squint,
                "tilt": self.eyes.tilt,
            },
            "brows": {
                "on": self.brows.on,
                "y": self.brows.y,
                "angle": self.brows.angle,
                "length": self.brows.length,
            },
            "mouth": {
                "y": self.mouth.y,
                "width": self.mouth.width,
                "curve": self.mouth.curve,
                "open": self.mouth.open,
                "wave": self.mouth.wave,
                "flick": self.mouth.flick,
            },
            "marks": list(self.marks),
        }


def _num(value: Any, fallback: float) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return float(fallback)
    if math.isnan(value) or math.isinf(value):
        return float(value)
    return float(value)


def clamp(value: float, limits: Sequence[float]) -> float:
    lo, hi = limits[0], limits[1]
    if math.isnan(value) or math.isinf(value):
        # face.ts uses Number.isFinite, so a non-finite value collapses to the
        # low end rather than clamping to the high one.
        return float(lo)
    return float(min(hi, max(lo, value)))


def clamp_to(key: str, value: float) -> float:
    return clamp(value, FACE_LIMITS[key])


def clamp_face(p: FaceParams) -> FaceParams:
    """Sanitise a whole face. A face can be ugly on purpose; never broken."""
    seen: list[str] = []
    for m in p.marks:  # dedupe, order-preserving, like `new Set`
        if m not in seen:
            seen.append(m)
    return replace(
        p,
        width=clamp_to("width", p.width),
        height=clamp_to("height", p.height),
        squish=clamp_to("squish", p.squish),
        tilt=clamp_to("tilt", p.tilt),
        gap=clamp_to("gap", p.gap),
        eyes=replace(
            p.eyes,
            x=clamp_to("eyeX", p.eyes.x),
            y=clamp_to("eyeY", p.eyes.y),
            size=clamp_to("eyeSize", p.eyes.size),
            squint=clamp_to("eyeSquint", p.eyes.squint),
            tilt=clamp_to("eyeTilt", p.eyes.tilt),
        ),
        brows=replace(
            p.brows,
            y=clamp_to("browY", p.brows.y),
            angle=clamp_to("browAngle", p.brows.angle),
            length=clamp_to("browLength", p.brows.length),
        ),
        mouth=replace(
            p.mouth,
            y=clamp_to("mouthY", p.mouth.y),
            width=clamp_to("mouthWidth", p.mouth.width),
            curve=clamp_to("mouthCurve", p.mouth.curve),
            open=clamp_to("mouthOpen", p.mouth.open),
            wave=clamp_to("mouthWave", p.mouth.wave),
            flick=clamp_to("mouthFlick", p.mouth.flick),
        ),
        marks=tuple(seen),
    )


# ---------------------------------------------------------------------------
# Drawing primitives
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Prim:
    """One drawable. ``stroke`` and ``fill`` carry SVG path data; ``dot`` is an
    ellipse, which is cheaper to state than to describe as arcs."""

    kind: str  # 'stroke' | 'fill' | 'dot'
    key: str
    d: str = ""
    w: float | None = None
    opacity: float | None = None
    cx: float = 0
    cy: float = 0
    rx: float = 0
    ry: float = 0


Pt = tuple[float, float]


def smooth(points: Sequence[Pt], closed: bool = False) -> str:
    """Catmull-Rom through the points, emitted as cubics.

    Sampling a curve into a polyline and stroking it looks faceted at print
    size, which is exactly the size this art is used at.
    """
    if len(points) < 2:
        return ""

    def pt(i: int) -> Pt:
        if closed:
            return points[(i + len(points)) % len(points)]
        return points[min(len(points) - 1, max(0, i))]

    d = f"M{fmt(points[0][0])},{fmt(points[0][1])}"
    last = len(points) if closed else len(points) - 1
    for i in range(last):
        p0, p1, p2, p3 = pt(i - 1), pt(i), pt(i + 1), pt(i + 2)
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        d += (
            f"C{fmt(c1[0])},{fmt(c1[1])} "
            f"{fmt(c2[0])},{fmt(c2[1])} "
            f"{fmt(p2[0])},{fmt(p2[1])}"
        )
    return f"{d}Z" if closed else d


def _signed_pow(value: float, exponent: float) -> float:
    """``Math.sign(v) * Math.abs(v) ** e``."""
    magnitude = abs(value) ** exponent
    if value > 0:
        return magnitude
    if value < 0:
        return -magnitude
    return 0.0


def outline_path(p: FaceParams) -> str:
    """A superellipse, drawn from the far side of the open loop round to the
    near side, so the gap is simply the part we never draw."""
    if p.gap >= NO_OUTLINE_AT:
        return ""
    n = 3.4  # squircle exponent
    gap_centre = 315  # top right
    half = p.gap / 2
    start = gap_centre + half
    end = gap_centre + 360 - half
    steps = 72
    pts: list[Pt] = []
    for i in range(steps + 1):
        deg = start + (end - start) * i / steps
        t = deg * RAD
        ct = math.cos(t)
        st = math.sin(t)
        # The pull: crown and chin move in opposite directions, so dragging the
        # top of the face stretches it like putty instead of just scaling it.
        ry = p.height + (p.squish if st < 0 else -p.squish)
        pts.append(
            (
                FACE_CX + p.width * _signed_pow(ct, 2 / n),
                FACE_CY + ry * _signed_pow(st, 2 / n),
            )
        )
    return smooth(pts, p.gap <= 0.5)


def _eye_prims(p: FaceParams, side: int) -> list[Prim]:
    cx = FACE_CX + side * p.eyes.x
    cy = p.eyes.y
    s = p.eyes.size
    open_ = 1 - 0.88 * p.eyes.squint
    key = "eyeL" if side < 0 else "eyeR"
    prims: list[Prim] = []

    if p.eyes.shape == "round":
        prims.append(
            Prim(kind="dot", cx=cx, cy=cy, rx=s * 0.62, ry=s * 0.62 * open_ + 0.6, key=key)
        )
    elif p.eyes.shape == "bar":
        h = s * 1.5 * open_
        prims.append(
            Prim(
                kind="stroke",
                d=f"M{fmt(cx)},{fmt(cy - h / 2)} L{fmt(cx)},{fmt(cy + h / 2)}",
                w=s * 0.95,
                key=key,
            )
        )
    elif p.eyes.shape == "tick":
        # The eye as a single flicked stroke.
        h = s * 1.35 * open_
        lean = s * 0.28
        prims.append(
            Prim(
                kind="stroke",
                d=(
                    f"M{fmt(cx - side * lean)},{fmt(cy - h / 2)} "
                    f"L{fmt(cx + side * lean)},{fmt(cy + h / 2)}"
                ),
                w=STROKE * 0.95,
                key=key,
            )
        )
    elif p.eyes.shape == "arc":
        # The happy squint.
        w = s * 1.35
        lift = s * (0.75 + 0.5 * open_)
        prims.append(
            Prim(
                kind="stroke",
                d=(
                    f"M{fmt(cx - w)},{fmt(cy + lift * 0.35)} "
                    f"Q{fmt(cx)},{fmt(cy - lift)} "
                    f"{fmt(cx + w)},{fmt(cy + lift * 0.35)}"
                ),
                key=key,
            )
        )
    elif p.eyes.shape == "line":
        w = s * 1.4
        prims.append(
            Prim(kind="stroke", d=f"M{fmt(cx - w)},{fmt(cy)} L{fmt(cx + w)},{fmt(cy)}", key=key)
        )
    elif p.eyes.shape == "cross":
        w = s * 1.05
        prims.append(
            Prim(
                kind="stroke",
                d=f"M{fmt(cx - w)},{fmt(cy - w)} L{fmt(cx + w)},{fmt(cy + w)}",
                key=f"{key}a",
            )
        )
        prims.append(
            Prim(
                kind="stroke",
                d=f"M{fmt(cx + w)},{fmt(cy - w)} L{fmt(cx - w)},{fmt(cy + w)}",
                key=f"{key}b",
            )
        )
    elif p.eyes.shape == "heart":
        # Two lobes and a point. Filled rather than stroked, because a heart
        # outlined in a 10-unit mono line at cuff-hit size closes up into a blob.
        w = s * 0.98
        h = s * (0.72 + 0.42 * open_)
        prims.append(
            Prim(
                kind="fill",
                d=(
                    f"M{fmt(cx)},{fmt(cy + h * 0.72)} "
                    f"C{fmt(cx - w * 1.18)},{fmt(cy - h * 0.1)} "
                    f"{fmt(cx - w * 0.62)},{fmt(cy - h * 1.05)} {fmt(cx)},{fmt(cy - h * 0.3)} "
                    f"C{fmt(cx + w * 0.62)},{fmt(cy - h * 1.05)} "
                    f"{fmt(cx + w * 1.18)},{fmt(cy - h * 0.1)} {fmt(cx)},{fmt(cy + h * 0.72)} Z"
                ),
                key=key,
            )
        )
    elif p.eyes.shape == "spiral":
        # Two and a bit turns — the "I am not really here" eye.
        turns = 2.25
        pts: list[Pt] = []
        steps = 26
        for i in range(steps + 1):
            t = (i / steps) * turns * 2 * math.pi
            rad = (s * 1.1 * i) / steps
            pts.append((cx + rad * math.cos(t), cy + rad * math.sin(t)))
        prims.append(Prim(kind="stroke", d=smooth(pts), w=STROKE * 0.7, key=key))
    return prims


def _wink_prim(p: FaceParams, side: int) -> Prim:
    """A shut eye: the lid as one arc."""
    cx = FACE_CX + side * p.eyes.x
    cy = p.eyes.y
    w = p.eyes.size * 1.25
    return Prim(
        kind="stroke",
        d=(
            f"M{fmt(cx - w)},{fmt(cy + 2)} "
            f"Q{fmt(cx)},{fmt(cy - p.eyes.size * 1.15)} "
            f"{fmt(cx + w)},{fmt(cy + 2)}"
        ),
        key="eyeL" if side < 0 else "eyeR",
    )


def _brow_prim(p: FaceParams, side: int) -> Prim:
    cx = FACE_CX + side * p.eyes.x
    half = p.brows.length / 2
    # Positive angle drops the inner end. Mirrored so both brows read the same.
    rise = math.tan(p.brows.angle * RAD) * half
    inner = (cx + side * -half, p.brows.y + rise)
    outer = (cx + side * half, p.brows.y - rise)
    return Prim(
        kind="stroke",
        d=f"M{fmt(inner[0])},{fmt(inner[1])} L{fmt(outer[0])},{fmt(outer[1])}",
        key="browL" if side < 0 else "browR",
    )


def _mouth_points(p: FaceParams, lip_offset: float = 0) -> list[Pt]:
    half = p.mouth.width / 2
    steps = 18
    pts: list[Pt] = []
    for i in range(steps + 1):
        t = i / steps
        x = FACE_CX - half + p.mouth.width * t
        # Parabola through the ends: 0 at both, 1 in the middle.
        bow = 4 * t * (1 - t)
        wave = math.sin(t * math.pi * 3) * 7 * p.mouth.wave * (0.35 + bow)
        pts.append((x, p.mouth.y + bow * p.mouth.curve * 30 + wave + lip_offset * bow))
    return pts


def mouth_prims(p: FaceParams) -> list[Prim]:
    if p.mouth.open > 0.02:
        # Open mouth: the line becomes the upper lip and a mirrored lower lip
        # closes the shape, so "open" reads as a hole rather than a thick line.
        upper = _mouth_points(p)
        lower = list(reversed(_mouth_points(p, 14 + p.mouth.open * 46)))
        lower_d = smooth(lower)
        if lower_d.startswith("M"):
            lower_d = "L" + lower_d[1:]
        return [Prim(kind="fill", d=f"{smooth(upper)} {lower_d} Z", key="mouth")]

    pts = _mouth_points(p)
    d = smooth(pts)
    if p.mouth.flick > 0.01:
        # Carry the stroke past the corner and upwards, the way a pen leaves
        # the paper.
        ex, ey = pts[-1]
        d += f" L{fmt(ex + p.mouth.flick * 11)},{fmt(ey - p.mouth.flick * 17)}"
    return [Prim(kind="stroke", d=d, key="mouth")]


def _mark_prims(p: FaceParams) -> list[Prim]:
    out: list[Prim] = []
    eye_l = FACE_CX - p.eyes.x
    eye_r = FACE_CX + p.eyes.x

    # Marks hang off the rim of the face — but with no outline there is no rim,
    # and a sweat drop parked where the edge used to be just floats in space.
    bare = p.gap >= NO_OUTLINE_AT
    span_x = (
        min(p.width, max(p.eyes.x + p.eyes.size, p.mouth.width / 2) + 12) if bare else p.width
    )
    span_y = (
        min(p.height, max(p.mouth.y - FACE_CY, FACE_CY - p.eyes.y + p.eyes.size) + 10)
        if bare
        else p.height
    )

    for mark in p.marks:
        if mark == "tear":
            x = eye_l
            y = p.eyes.y + p.eyes.size + 12
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(x)},{fmt(y)} "
                        f"C{fmt(x + 9)},{fmt(y + 12)} {fmt(x + 8)},{fmt(y + 26)} {fmt(x)},{fmt(y + 26)} "
                        f"C{fmt(x - 8)},{fmt(y + 26)} {fmt(x - 9)},{fmt(y + 12)} {fmt(x)},{fmt(y)} Z"
                    ),
                    key="tear",
                )
            )
        elif mark == "sweat":
            x = FACE_CX + span_x * 0.72
            y = FACE_CY - span_y * 0.52
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(x)},{fmt(y)} "
                        f"C{fmt(x + 8)},{fmt(y + 10)} {fmt(x + 7)},{fmt(y + 22)} {fmt(x)},{fmt(y + 22)} "
                        f"C{fmt(x - 7)},{fmt(y + 22)} {fmt(x - 8)},{fmt(y + 10)} {fmt(x)},{fmt(y)} Z"
                    ),
                    key="sweat",
                )
            )
        elif mark == "blush":
            y = p.eyes.y + p.eyes.size + 20
            out.append(Prim(kind="dot", cx=eye_l - 6, cy=y, rx=13, ry=7, opacity=0.5, key="blushL"))
            out.append(Prim(kind="dot", cx=eye_r + 6, cy=y, rx=13, ry=7, opacity=0.5, key="blushR"))
        elif mark == "static":
            # Interference across the face — the overwhelmed look.
            for i in range(3):
                y = FACE_CY - 18 + i * 26
                w = span_x * (0.82 if i == 1 else 0.6)
                out.append(
                    Prim(
                        kind="stroke",
                        d=f"M{fmt(FACE_CX - w)},{fmt(y)} L{fmt(FACE_CX + w)},{fmt(y)}",
                        w=STROKE * 0.55,
                        opacity=0.55,
                        key=f"static{i}",
                    )
                )
        elif mark == "zzz":
            base = FACE_CX + span_x * 0.62
            top = FACE_CY - span_y * 0.72
            for i in range(3):
                s = 9 + i * 5
                x = base + i * 5
                y = top - i * 20
                out.append(
                    Prim(
                        kind="stroke",
                        d=(
                            f"M{fmt(x - s)},{fmt(y - s)} L{fmt(x + s)},{fmt(y - s)} "
                            f"L{fmt(x - s)},{fmt(y + s)} L{fmt(x + s)},{fmt(y + s)}"
                        ),
                        w=STROKE * 0.6,
                        key=f"z{i}",
                    )
                )
        elif mark == "tongue":
            # Hung from the middle of the mouth, which is where the mouth's own
            # bow peaks — so it follows a grin up and a grimace down instead of
            # floating at a fixed height.
            mid_y = p.mouth.y + p.mouth.curve * 30
            # Narrow and deep. Wider than this and it stops reading as a tongue
            # and starts reading as a chin — it has to clear the 10-unit mouth
            # stroke it hangs off by enough to be a separate shape.
            w = min(13, p.mouth.width * 0.2)
            drop = w * 2.4
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(FACE_CX - w)},{fmt(mid_y - 1)} "
                        f"C{fmt(FACE_CX - w)},{fmt(mid_y + drop)} "
                        f"{fmt(FACE_CX + w)},{fmt(mid_y + drop)} {fmt(FACE_CX + w)},{fmt(mid_y - 1)} Z"
                    ),
                    key="tongue",
                )
            )
        elif mark == "sparkle":
            x = FACE_CX + span_x * 0.74
            y = FACE_CY - span_y * 0.62
            s = 14
            out.append(
                Prim(
                    kind="fill",
                    d=(
                        f"M{fmt(x)},{fmt(y - s)} Q{fmt(x + 2)},{fmt(y - 2)} {fmt(x + s)},{fmt(y)} "
                        f"Q{fmt(x + 2)},{fmt(y + 2)} {fmt(x)},{fmt(y + s)} "
                        f"Q{fmt(x - 2)},{fmt(y + 2)} {fmt(x - s)},{fmt(y)} "
                        f"Q{fmt(x - 2)},{fmt(y - 2)} {fmt(x)},{fmt(y - s)} Z"
                    ),
                    key="sparkle",
                )
            )
    return out


@dataclass(frozen=True)
class Spin:
    """A rotation about a point, in the form every renderer can use."""

    deg: float
    cx: float
    cy: float


@dataclass(frozen=True)
class FaceGeometry:
    tilt: float
    outline: Prim | None
    eyes_left: list[Prim]
    eyes_right: list[Prim]
    eye_rotation: tuple[Spin, Spin]  # left, right
    rest: list[Prim]

    def all_prims(self) -> Iterable[Prim]:
        if self.outline:
            yield self.outline
        yield from self.eyes_left
        yield from self.eyes_right
        yield from self.rest


def build_face(raw: FaceParams) -> FaceGeometry:
    p = clamp_face(raw)
    outline_d = outline_path(p)
    return FaceGeometry(
        tilt=p.tilt,
        outline=Prim(kind="stroke", d=outline_d, key="outline") if outline_d else None,
        # A wink is the one asymmetry the face allows: eyes are otherwise always
        # mirrored, because independent eyes read as a bug rather than a choice.
        eyes_left=[_wink_prim(p, -1)] if "wink" in p.marks else _eye_prims(p, -1),
        eyes_right=_eye_prims(p, 1),
        eye_rotation=(
            Spin(deg=-p.eyes.tilt, cx=FACE_CX - p.eyes.x, cy=p.eyes.y),
            Spin(deg=p.eyes.tilt, cx=FACE_CX + p.eyes.x, cy=p.eyes.y),
        ),
        rest=[
            *([_brow_prim(p, -1), _brow_prim(p, 1)] if p.brows.on else []),
            *mouth_prims(p),
            *_mark_prims(p),
        ],
    )
